# Site settings
title: Sriram
description: Android developer—among other things 
url: 'http://srir.am' 
baseurl: '/'
google_analytics: 'UA-75982361-1'

author:
  name: 'Sriram'
  email: 'http://www.google.com/recaptcha/mailhide/d?k=01TI6XRnC-LUp69Xi86ASbbw==&c=cnhU1J9niLd39nHquiudPtt6cEK9h45aThd6dkI8i8Y='
  twitter_username: 
  github_username:  SriramBms
  linkedin_username:  sriramsh
  dribbble_username:

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
